/**
 * Created by usman on 3/5/16.
 */
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var ClientSchema = new Schema({
    fname: { type: String },
    mname: { type: String },
    lname: { type: String },
    prefname: { type: String },
    dob: {type: Date},
    sex: { type: String },
    ssn: { type: String },
    address_street: { type: String },
    address_street2: { type: String },
    address_city: { type: String },
    address_state: { type: String },
    address_zip: { type: String },
    phone1: { type: Number },
    phone2: { type: Number },
    ccu: {type: Schema.Types.ObjectId, null:true},
    startdate: { type: Date},
    ccu_caseworker: { type: String },
    photo: { type: String },
    paymethod: { type: String },
    status: { type: String },
    livingarrangement: { type: String },
    notes: { type: String},
    mconame: { type: String },
    mcoprocedurecodes: { type: String },
    medicaidnumber: { type: String },
    mco_casemanager: { type: String },
    mco_diagnosis: { type: String },
    mco_memberid: {type: Schema.Types.ObjectId, null:true},
    mco_medicarenumber: { type: String },
    mco_authnumber: { type: String },
    mco_casemanager: { type: String },
    mco_casemanagerphone: { type: String },
    mco_comments: { type: String },
    co_id: {type: Schema.Types.ObjectId, null:true}
});

/*
    fname: "John",
    mname: "Matthew",
    lname: "Doe",
    prefname: "Jack",
    dob_mo: "12",
    dob_da: "18",
    dob_yr: "1951",
    sex: "male",
    ssn: "329-76-3271",
    address_street: "12951 S. McVickers Ave.",
    address_street2: "",
    address_city: "Palos Heights",
    address_state: "13",
    address_zip: "60463-2921",
    phone1: "7083710681",
    phone2: "7083269299",
    ccu: "1",
    startdate: "08/17/2014",
    ccu_caseworker: "Sarah SMith",
    photo: "0",
    paymethod: "",
    status: "",
    livingarrangement: "",
    notes: "blah blah blah",
    mconame: "",
    mcoprocedurecodes: "",
    medicaidnumber: "",
    mco_casemanager: "",
    mco_diagnosis: "",
    mco_memberid: "",
    mco_medicarenumber: "",
    mco_authnumber: "",
    mco_casemanager: "",
    mco_casemanagerphone: "",
    mco_comments: "",
    co_id: "1"
 */
mongoose.model('Client', ClientSchema);
